version: '3.9'

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    container_name: caddy
    env_file:
      - caddy.env 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    secrets:
      - vw_admin_token
    depends_on:
      - caddy
    environment:
      WEBSOCKET_ENABLED: "true"
      ADMIN_TOKEN_FILE: /run/secrets/vw_admin_token
    volumes:
      - ./vaultwarden/data:/data
  
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    secrets:
      - pg_user_password
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - /mnt/brgdrf/postgres:/var/lib/postgresql/data

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: always
    depends_on:
      - postgres
    secrets:
      - nc_jwt_secret
    env_file:
      - nocodb.env
    ports:
      - 8080:8080
    volumes:
      - /mnt/brgdrf/nc:/usr/app/data
  
secrets:
  vw_admin_token:
    file: ./secrets/vw_admin_token
  pg_user_password:
    file: ./secrets/pg_user_password
  nc_jwt_secret:
    file: ./secrets/nc_jwt_secret
